apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    tad.gitops.set/image: ".spec.template.spec.containers[0].image"
    tad.gitops.get/image: ".spec.template.spec.containers[0].image"
    tad.gitops.set/replicas: ".spec.replicas"
    tad.gitops.get/replicas: ".spec.replicas"
  name: go-ffxezyup
spec:
  replicas: 1
  template:
    spec:
      containers:
        - image: quay.io/rhtap_qe/go-ffxezyup:d52ec49897bb0ecdcd5b5a88a34da00b69d92223@sha256:cee12b6c76525928942845db70cd475f97265281af83bde59bef38234286b907
          name: container-image
